############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Projects"
url = "/projects"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 4

# footer menu
[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 1

[[footer]]
name = "Socials"
url = "/socials"
weight = 2
